# GAME SETTING
WINDOW_WIGHT = 1000
WINDOW_HEIGHT = 600
HALF_WINDOW_WIGHT = WINDOW_WIGHT // 2
HALF_WINDOW_HEIGHT = WINDOW_HEIGHT // 2
FPS = 60
BLOCK_SIDE = 25
HALF_BLOCK_SIDE = BLOCK_SIDE / 2

# PLAYER SETTING
camera_pos = (HALF_WINDOW_WIGHT, HALF_WINDOW_HEIGHT)
camera_angle = 0

# PLAYER SETTING
player_pos = (HALF_WINDOW_WIGHT, HALF_WINDOW_HEIGHT)
player_angle = 0
player_angle_perframe = 0.07
player_speed = BLOCK_SIDE / 10
sprint = 1.2